controller:
  serviceAccount:
    create: false
    name: jenkins
  
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
  
  serviceType: NodePort
  nodePort: 32000
  
agent:
  podName: "jenkins-agent"
  
persistence:
  enabled: true
  size: 8Gi
  storageClass: gp2
