apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
  namespace: db-ns
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""        # Empty for static binding 
  hostPath:
    path: /tmp/my-pv
    type: DirectoryOrCreate